language: php

php:
  - 7.1
  - 7.2

branches:
  only:
    master

sudo: false

cache:
  directories:
        - $HOME/.composer/cache

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS homestead DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;'


install:
  - travis_retry composer install --no-interaction --prefer-source
  - cp .env.travis .env
  - php artisan migrate


script: vendor/bin/phpunit
