language: php

php:
  - 7.1
  - 7.2

branches:
  only:
    master

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE homestead;'

install:
  - travis_retry composer install --no-interaction --prefer-source
  - cp .env.travis .env
  - composer keys
  - php artisan migrate


script: vendor/bin/phpunit
